apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak

spec:
  entryPoints:
  - websecure
  routes:
  # 公開エンドポイント (qualia.harvestasya.org)
  # 認証なしでアクセス可能なパス
  # TODO: 本番では /realms/, /resources/, /.well-known/, /js/ のみに制限
  - kind: Rule
    match: Host(`qualia.harvestasya.org`)
    services:
    - name: keycloak-keycloakx-http
      port: 80
    middlewares:
    - name: security-headers
      namespace: traefik

  # 管理コンソール (qualia-admin.harvestasya.org)
  # TODO: 将来的にIP制限や追加認証を実装
  - kind: Rule
    match: Host(`qualia-admin.harvestasya.org`)
    services:
    - name: keycloak-keycloakx-http
      port: 80
    middlewares:
    - name: security-headers
      namespace: traefik

  tls:
    secretName: harvestasya-wildcard-tls
