apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
- namespace.yaml
- cnpg-cluster.yaml
- external-secret.yaml
# Migrated to ExternalSecret
# - secret-keycloak-admin.yaml
- middleware.yaml
- ingressroute.yaml

helmCharts:
# https://github.com/codecentric/helm-charts/tree/master/charts/keycloakx
- name: keycloakx
  releaseName: keycloak
  namespace: keycloak
  version: 7.1.7
  repo: https://codecentric.github.io/helm-charts
  valuesFile: values.yaml
