apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: keycloak-admin
  labels:
    app.kubernetes.io/name: keycloak
spec:
  itemPath: "vaults/5mixaulvwor6zfvbfmtqlksdy4/items/v2y2pu55qrgu2xhnfnx3qlvtfe"
