apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-machine-learning
    app.kubernetes.io/component: machine-learning
    app.kubernetes.io/part-of: immich
spec:
  selector:
    app.kubernetes.io/name: immich-machine-learning
  ports:
  - name: http
    port: 3003
    protocol: TCP
    targetPort: http
