apiVersion: v1
kind: Service
metadata:
  name: immich-server-metrics
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-server
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: immich
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app.kubernetes.io/name: immich-server
  ports:
  - name: metrics-api
    port: 8081
    protocol: TCP
    targetPort: metrics-api
  - name: metrics-micro
    port: 8082
    protocol: TCP
    targetPort: metrics-micro
