apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: airq-exporter
  namespace: temporis
spec:
  components:
  - name: airq-exporter
    type: webservice
    properties:
      image: ghcr.io/suzutan/m5stack_airq_exporter:latest
      port: 8080
      cpu: "100m"
      memory: 50Mi
      env:
      - name: AIRQ_DATA_URL
        valueFrom:
          secretKeyRef:
            name: airq-data-url
            key: AIRQ_DATA_URL
    traits:
    - type: annotations
      properties:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
