apiVersion: apps/v1
kind: Deployment
metadata:
  name: airq-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: airq-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: airq-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
    spec:
      containers:
      - name: airq-exporter
        image: ghcr.io/suzutan/m5stack_airq_exporter:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi
        env:
        - name: AIRQ_DATA_URL
          valueFrom:
            secretKeyRef:
              name: airq-data-url
              key: AIRQ_DATA_URL
