apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airq-data-url-external-secret
  namespace: temporis
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: airq-data-url
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: temporis/airq-data-url
