apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
- namespace.yaml

helmCharts:
- name: flux2
  releaseName: flux
  namespace: flux-system
  version: 2.17.2
  repo: https://fluxcd-community.github.io/helm-charts
  includeCRDs: true
  valuesFile: values.yaml
