apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: artonelico

spec:
  routes:
  - kind: Rule
    match: Host(`artonelico.harvestasya.org`)
    services:
    - name: artonelico-proxy
      port: 8006
      scheme: https
      serversTransport: artonelico-skip-verify
