apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
- namespace.yaml
- cluster-secret-store.yaml

helmCharts:
# https://external-secrets.io/latest/introduction/getting-started/
- name: external-secrets
  releaseName: external-secrets
  namespace: external-secrets
  version: 1.3.1
  repo: https://charts.external-secrets.io
  includeCRDs: true
  valuesFile: values.yaml
