apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: pomerium-transport
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: navidrome-pomerium
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`navidrome.harvestasya.org`)
    services:
    - name: pomerium-proxy
      namespace: pomerium
      port: 443
      scheme: https
      serversTransport: pomerium-transport
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: navidrome-filebrowser-pomerium
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`navidrome-filebrowser.harvestasya.org`)
    services:
    - name: pomerium-proxy
      namespace: pomerium
      port: 443
      scheme: https
      serversTransport: pomerium-transport
