apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: navidrome

resources:
- namespace.yaml
- service-navidrome.yaml
- ingressroute-filebrowser.yaml
- ingressroute-navidrome.yaml
