apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb2-auth
  namespace: temporis
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: influxdb2-auth
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: temporis/influxdb2-auth
