apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: temporis

resources:
- serviceaccount.yaml
- service.yaml
- pvc.yaml
- statefulset.yaml
- external-secret.yaml
- ingressroute.yaml
