apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: temporis

resources:
- external-secret.yaml
- ingressroute.yaml

helmCharts:
- name: influxdb2
  releaseName: influxdb2
  namespace: temporis
  version: 2.1.2
  repo: https://helm.influxdata.com/
  valuesFile: values.yaml
