apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: influxdb2
      app.kubernetes.io/name: influxdb2
  serviceName: influxdb2
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: influxdb2
        app.kubernetes.io/name: influxdb2
    spec:
      serviceAccountName: influxdb2
      containers:
      - name: influxdb2
        image: influxdb:2.7.4-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8086
          name: http
          protocol: TCP
        env:
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: setup
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: admin
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-password
              name: influxdb2-auth
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: influxdata
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: default
        - name: DOCKER_INFLUXDB_INIT_RETENTION
          value: 0s
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              key: admin-token
              name: influxdb2-auth
        - name: INFLUXD_BOLT_PATH
          value: /var/lib/influxdb2/influxd.bolt
        - name: INFLUXD_ENGINE_PATH
          value: /var/lib/influxdb2
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - name: data
          mountPath: /var/lib/influxdb2
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: influxdb2
