
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm

data:
  applicationsetcontroller.log.level: debug
  controller.log.level: debug
  reposerver.log.level: debug
  server.log.level: debug
  server.insecure: "true"
