apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argocd-rbac-cm

# https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/
data:
  policy.default: role:readonly
  policy.csv: |-
    p, role:admin, *, *, *, allow

    g, /argocd/admin, role:admin
