apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: asf

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- pvc.yaml
- ingress.yaml

labels:
- pairs:
    app.kubernetes.io/name: asf
  includeSelectors: true
  includeTemplates: true
