apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- kustomizeconfig.yaml

namespace: temporis

resources:
- cr.yaml
- crb.yaml
- ingress-pomerium.yaml
- statefulset.yaml
- service.yaml
- serviceaccount.yaml

images:
- name: quay.io/prometheus/prometheus
  newTag: v3.9.1
- name: quay.io/thanos/thanos
  newTag: v0.40.1

configMapGenerator:
- name: prometheus-config
  files:
  - config/prometheus.yaml


labels:
- pairs:
    app.kubernetes.io/name: prometheus
  includeSelectors: true
- pairs:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: temporis
  includeSelectors: false
