apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- airq-exporter
- grafana
- influxdb
- node-exporter
- prometheus
# - prometheus-exporter-kube-system
- remo-exporter
- ingressroute-pomerium.yaml


labels:
- pairs:
    app.kubernetes.io/managed-by: kustomize
  includeSelectors: false
