apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: onepassword
resources:
- ../../manifests/onepassword-operator

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: op-credentials
  files:
  - 1password-credentials.json=secrets/1password-credentials.json.b64enc
- name: onepassword-token
  files:
  - token=secrets/token
