apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homarr-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: homarr/homarr-secret
