apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  url: http://prometheus:9090/
  access: proxy
  isDefault: true
  jsonData:
    httpMethod: POST
    timeInterval: 30s
- name: InfluxDB
  type: influxdb
  uid: bdn6s58lflekge
  url: http://influxdb2:80
  access: proxy
  jsonData:
    version: Flux
    organization: influxdata
    defaultBucket: default
    tlsSkipVerify: true
  secureJsonData:
    token: $INFLUXDB_TOKEN
