apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: config-external-secret
  namespace: ddns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: config
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: ddns/cloudflare-ddns
