apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: asf

resources:
- ingress.yaml
- ingressroute.yaml
- deployment.yaml
- namespace.yaml
- persistentvolumeclaim.yaml
- service.yaml
- service-traefik-proxy.yaml

images:
- name: justarchi/archisteamfarm
  newTag: 6.3.0.1

labels:
- pairs:
    app.kubernetes.io/name: asf
  includeSelectors: true
  includeTemplates: true


