apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: asf

resources:
# K8s native resources
- namespace.yaml
- pvc.yaml
- ingressroute.yaml

# KubeVela Application
- application.yaml

labels:
- pairs:
    app.kubernetes.io/name: asf
  includeSelectors: true
  includeTemplates: true
