apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-server
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: immich
spec:
  selector:
    app.kubernetes.io/name: immich-server
  ports:
  - name: http
    port: 2283
    protocol: TCP
    targetPort: http
