apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflared

resources:
- deployment.yaml
- namespace.yaml
- external-secret.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: cloudflared
images:
- name: cloudflare/cloudflared
  newTag: 2026.2.0
