apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflared-tunnel-secret
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  itemPath: vaults/5mixaulvwor6zfvbfmtqlksdy4/items/zxwgthayn6xlt7sztqjta3inlq
