apiVersion: v1
kind: Service
metadata:
  name: step-certificates-acme
  namespace: step-ca
  labels:
    app.kubernetes.io/name: step-certificates
    app.kubernetes.io/instance: step-certificates
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 9000
    protocol: TCP
  selector:
    app.kubernetes.io/name: step-certificates
    app.kubernetes.io/instance: step-certificates
