apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: step-certificates-config
  namespace: step-ca
spec:
  itemPath: "vaults/5mixaulvwor6zfvbfmtqlksdy4/items/2n33wjnxjubdch4z4im4y75xb4"
