apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: step-certificates-ca-password
  namespace: step-ca
spec:
  itemPath: "vaults/5mixaulvwor6zfvbfmtqlksdy4/items/prjz6blfjeymzamfibipoyhgj4"
