apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: step-certificates-secrets
  namespace: step-ca
spec:
  itemPath: "vaults/5mixaulvwor6zfvbfmtqlksdy4/items/qdlsa4kuvl5cqz4h2pxnrqgbq4"
