apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: step-certificates-certs
  namespace: step-ca
spec:
  itemPath: "vaults/5mixaulvwor6zfvbfmtqlksdy4/items/awbihfdgr7se6lbqfuks23fwru"
