apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: step-issuer-provisioner
  namespace: step-ca
spec:
  itemPath: "vaults/5mixaulvwor6zfvbfmtqlksdy4/items/djxs6dcd2ydczf2l4yqbz5oady"
