apiVersion: certmanager.step.sm/v1beta1
kind: StepClusterIssuer
metadata:
  name: step-issuer
spec:
  # step-certificates CA URL
  url: https://step-certificates.step-ca.svc.cluster.local
  # CA bundle (root CA + intermediate CA certificate)
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJnRENDQVNhZ0F3SUJBZ0lSQUtSVlQrTmExa2d0bW8vVFQ4YjhPUW93Q2dZSUtvWkl6ajBFQXdJd0hqRWMKTUJvR0ExVUVBeE1UU0dGeWRtVnpkR0F6ZVdFZ1VtOXZkQ0JEUVRBZUZ3MHlOVEV5TWpReE56STRNekZhRncwegpOVEV5TWpJeE56STRNekZhTUI0eEhEQWFCZ05WQkFNVEUwaGhjblpsYzNSaGMzbGhJRkp2YjNRZ1EwRXdXVEFUCkJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNVN0p5Vk51V29UUURFOWY2bnpnWGlBUUZ3azFOaDBNU1EKbnZuTFZlMDRaWUo5M3krdkZSOFphdUU2WXhWVVVSdTQ1VmVEVm5PV3l2a2NuaFpmbm5RWm8wVXdRekFPQmdOVgpIUThCQWY4RUJBTUNBUVl3RWdZRFZSMFRBUUgvQkFnd0JnRUIvd0lCQVRBZEJnTlZIUTRFRmdRVTJHT0I2SEJLCjNPR05jWUREMkVoOGlKODRrYVV3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnSnRSWXM2RkZ1bEU4YmN4Q1J2VEIKelo3Ym1OTlFYVXdRWWJSMDUzWmVxL1lDSVFEQUdpdWI1SUdqZ0xwcE9qY3FaQWhQRkM1Y20vNGlIaU9iMTJVVAo0V3NnaGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCcVRDQ0FVK2dBd0lCQWdJUkFOVHBUZ2FNUCt6cXozOWREQTZTc3dVd0NnWUlLb1pJemowRUF3SXdIakVjCk1Cb0dBMVVFQXhNVFNHRnlkbVZ6ZEdGemVXRWdVbTl2ZENCRFFUQWVGdzB5TlRFeU1qUXhOek13TlRkYUZ3MHoKTURFeU1qTXhOek13TkRsYU1DWXhKREFpQmdOVkJBTVRHMGhoY25abGMzUmhjM2xoSUVsdWRHVnliV1ZrYVdGMApaU0JEUVRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkxLQjF2RnRQTjZIKzZCMjRkSWwxOGJMCnZMS0RuUU1vaWtReW5hZHpYNUhsL0F3b3RZMms4QzBUUWxBQmEzR2pqd3htOUdBenVKQ2VkVzNBMGppUngvV2oKWmpCa01BNEdBMVVkRHdFQi93UUVBd0lCQmpBU0JnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQU1CMEdBMVVkRGdRVwpCQlM0alhhMkdDVTczYW02enNWdkVoWnFOdFBWVHpBZkJnTlZIU01FR0RBV2dCVFlZNEhvY0VyYzRZMXhnTVBZClNIeUluemlScFRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlCc2FmbFZaOXA3R2NnWi81ZVd5b2pHWUo0OFBEaE4KbjRqcDNRN3E4RldpT3dJaEFMSGxqWGdOTExseHhXb1lmTDJOOXRlVmkzZTF4Q1JETXhEa3o5SENNc25SCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  # Provisioner configuration
  provisioner:
    name: step-issuer@harvestasya.org
    kid: VjFDb15x_MB3BOIE3p90ucyEBF4q-sG-5InHhClzqyg
    passwordRef:
      name: step-issuer-provisioner
      key: provisioner-password.txt
      namespace: step-ca
