apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: step-certificates-certs
  namespace: step-ca-identity
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: step-certificates-certs
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: step-ca-identity/step-certificates-certs
