apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: outline
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - outline.harvestasya.org
    secretName: outline-tls
  rules:
  - host: outline.harvestasya.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: outline
            port:
              name: http