apiVersion: v1
kind: Secret
metadata:
  name: outline-secret
type: Opaque
stringData:
  secret-key: "132b1c3d216a6fbba8d39d0590d81dcce48d2e1a4eb59b568e9253023b85064a"
  utils-secret: "1f93543704bb0bc4dc57e03fea6b89230bb5d5e6d5f1fd6639f4a2bb502c87ed"
  database-url: "postgres://outline:85ad674f1eea9f64ae3a0f126f472632@postgresql:5432/outline"
  redis-url: "redis://:5871b2573a8bcf5a8fdc0badfa5261fc@redis-master:6379"