apiVersion: v1
kind: Secret
metadata:
  name: outline-oidc-secret
type: Opaque
stringData:
  OIDC_CLIENT_ID: "outline"
  OIDC_CLIENT_SECRET: "changeme"
  OIDC_AUTH_URI: "https://authentik.harvestasya.org/application/o/authorize/"
  OIDC_TOKEN_URI: "https://authentik.harvestasya.org/application/o/token/"
  OIDC_USERINFO_URI: "https://authentik.harvestasya.org/application/o/userinfo/"
  OIDC_DISPLAY_NAME: "Authentik"
  OIDC_USERNAME_CLAIM: "preferred_username"
  OIDC_SCOPES: "openid profile email"