apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nanomdm-pg
  namespace: nanomdm
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      postInitApplicationSQLRefs:
        configMapRefs:
        - name: nanomdm-schema
          key: schema.sql
