apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nanomdm-server-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nanomdm-server-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: nanomdm/server-secret
