apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nanomdm
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`nexus-beta.harvestasya.org`)
    kind: Rule
    services:
    - name: nanomdm
      port: 9000
    middlewares:
    - name: security-headers
      namespace: traefik
  tls:
    secretName: harvestasya-wildcard-tls
