apiVersion: v1
kind: Service
metadata:
  name: nanomdm
  labels:
    app.kubernetes.io/name: nanomdm
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: mdm
    protocol: TCP
    name: mdm
  selector:
    app.kubernetes.io/name: nanomdm
    app.kubernetes.io/component: server
---
apiVersion: v1
kind: Service
metadata:
  name: nanomdm-operator
  labels:
    app.kubernetes.io/name: nanomdm
    app.kubernetes.io/component: operator
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: webhook
    protocol: TCP
    name: webhook
  selector:
    app.kubernetes.io/name: nanomdm
    app.kubernetes.io/component: operator
