apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: harvestasya-root-ca
  namespace: cert-manager
spec:
  itemPath: "vaults/5mixaulvwor6zfvbfmtqlksdy4/items/nfsxpva676lgrslko46fa7q7xq"
type: kubernetes.io/tls
