apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: temporis

resources:
- cr.yaml
- crb.yaml
- deployment.yaml
- ingress.yaml
- pvc.yaml
- role.yaml
- rolebinding.yaml
- external-secret.yaml
# Migrated to ExternalSecret
# - secret-grafana.yaml
- service.yaml
- serviceaccount.yaml

configMapGenerator:
- name: grafana
  files:
  - config/grafana.ini
- name: grafana-dashboards-1
  files:
  - dashboards/airq-exporter.json
  - dashboards/node-exporter.json
  - dashboards/remo-exporter.json
  - dashboards/proxmox-flux.json
- name: grafana-dashboard-provider
  files:
  - config/dashboard-provider.yaml
- name: grafana-datasource
  files:
  - config/datasource.yaml

images:
- name: docker.io/grafana/grafana
  newTag: 12.3.2

labels:
- pairs:
    app.kubernetes.io/name: grafana
  includeSelectors: true
- pairs:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: temporis
  includeSelectors: false
