apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system
resources:
- cr.yaml
- crb.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml

images:
- name: registry.k8s.io/kube-state-metrics/kube-state-metrics
  newTag: v2.18.0

labels:
- pairs:
    app.kubernetes.io/name: kube-state-metrics
  includeSelectors: true
