apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - group: external-secrets.io
    kind: ExternalSecret
    jsonPointers:
    - /spec/dataFrom/0/extract/conversionStrategy
    - /spec/dataFrom/0/extract/decodingStrategy
    - /spec/dataFrom/0/extract/metadataPolicy
    - /spec/target/deletionPolicy
  project: default
  source:
    repoURL: https://github.com/suzutan/infra
    targetRevision: HEAD
    path: k8s/manifests/cloudflared
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
