apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
- namespace.yaml
- ipaddresspool.yaml
- l2advertisement.yaml

helmCharts:
- name: metallb
  releaseName: metallb
  namespace: metallb-system
  version: 0.14.9
  repo: https://metallb.github.io/metallb
  includeCRDs: true
  valuesFile: values-metallb.yaml
