apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pomerium-wildcard-tls
spec:
  secretName: pomerium-wildcard-tls
  dnsNames:
  - '*.harvestasya.org'
  issuerRef:
    name: step-issuer
    kind: StepClusterIssuer
    group: certmanager.step.sm
