apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pomerium-authenticate-tls
spec:
  secretName: pomerium-authenticate-tls
  dnsNames:
  - 'authenticate.harvestasya.org'
  issuerRef:
    name: step-issuer
    kind: StepClusterIssuer
    group: certmanager.step.sm
