apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pomerium-keycloak-oidc
  namespace: pomerium
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pomerium-keycloak-oidc
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: pomerium/pomerium-keycloak-oidc
