apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pomerium

resources:
# Pomerium Ingress Controller (official kustomize base)
# https://github.com/pomerium/ingress-controller
- https://github.com/pomerium/ingress-controller/config/default?ref=v0.32.0
- onepassworditem-pomerium-idp.yaml
- certificate-authenticate.yaml
- pomerium-crd.yaml
