apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: pomerium-keycloak-oidc
  labels:
    app.kubernetes.io/name: pomerium
spec:
  itemPath: "vaults/5mixaulvwor6zfvbfmtqlksdy4/items/5y4ri2krmtvtcmwze2du46j6je"
