apiVersion: ingress.pomerium.io/v1
kind: Pomerium
metadata:
  name: global
spec:
  authenticate:
    url: https://authenticate.harvestasya.org
  identityProvider:
    provider: oidc
    url: https://accounts.harvestasya.org/realms/harvestasya
    secret: pomerium/pomerium-keycloak-oidc
  certificates:
  - pomerium/pomerium-wildcard-tls
  secrets: pomerium/bootstrap
  cookie:
    domain: harvestasya.org
