apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hsr-auto-claimer-config-external-secret
  namespace: hsr-auto-claimer
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hsr-auto-claimer-config
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: hsr-auto-claimer/hsr-auto-claimer-config
