apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-apps.yaml
- argocd.yaml
- asf.yaml
- authentik.yaml
- cert-manager.yaml
- cnpg-operator.yaml
- ddns.yaml
- echoserver.yaml
- fluxcd.yaml
- hsr-auto-claimer.yaml
- immich.yaml
- kube-state-metrics.yaml
- kube-vip.yaml
- kubevela.yaml
- n8n.yaml
- navidrome.yaml
- nfs-subdir-external-provisioner.yaml
- onepassword-operator.yaml
- step-ca.yaml
- temporis.yaml
- traefik.yaml
- voidauth.yaml
