apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-apps.yaml
- argocd.yaml
- asf.yaml
- authentik.yaml
- cert-manager.yaml
- cloudflared.yaml
- ddns.yaml
- echoserver.yaml
- local-path-storage.yaml
- navidrome.yaml
- onepassword-operator.yaml
- temporis.yaml
- traefik.yaml
