apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
- namespace.yaml
- ci-letsencrypt-prod.yaml
- ci-letsencrypt-staging.yaml
- external-secret.yaml
# Migrated to ExternalSecret
# - secret-cert-manager-cloudflare.yaml

helmCharts:
# https://cert-manager.io/docs/installation/helm/
- name: cert-manager
  releaseName: cert-manager
  namespace: cert-manager
  version: v1.19.2
  repo: https://charts.jetstack.io
  includeCRDs: true
  valuesFile: values.yaml
