apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cert-manager-cloudflare
  namespace: cert-manager
spec:
  itemPath: "vaults/5mixaulvwor6zfvbfmtqlksdy4/items/lpnij6xqynstehycgbg6p4wmna"
