apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fleet-mysql-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: fleet-mysql-secret
    creationPolicy: Owner
  data:
  - secretKey: mysql-root-password
    remoteRef:
      key: fleet/mysql-secret
      property: mysql-root-password
  - secretKey: mysql-password
    remoteRef:
      key: fleet/mysql-secret
      property: mysql-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fleet-valkey-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: fleet-valkey-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: fleet/valkey-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fleet-server-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: fleet-server-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: fleet/server-secret
