apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: suzutan-jp-wildcard-tls
spec:
  secretName: suzutan-jp-wildcard-tls
  dnsNames:
  - '*.suzutan.jp'
  issuerRef:
    name: step-issuer
    kind: StepClusterIssuer
    group: certmanager.step.sm
