apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nature-remo-token-external-secret
  namespace: temporis
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nature-remo-token
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: temporis/nature-remo-token
