apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: remo-exporter

spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`remo-exporter.harvestasya.org`)
    services:
    - name: remo-exporter
      port: 9352
    middlewares:
    - name: security-headers
      namespace: traefik

  tls:
    secretName: harvestasya-wildcard-tls
