# VelaUX - KubeVela Dashboard
# https://kubevela.io/docs/reference/addons/velaux
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: velaux
  namespace: vela-system
spec:
  components:
    - name: velaux-server
      type: webservice
      properties:
        image: oamdev/velaux:v1.9.5
        ports:
          - port: 8000
            expose: true
            protocol: TCP
      traits:
        - type: service-account
          properties:
            name: kubevela-vela-core
        - type: scaler
          properties:
            replicas: 1
