apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-secret
  namespace: couchdb
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: couchdb-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: couchdb/couchdb-secret
