apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cosmosphere
  labels:
    app.kubernetes.io/name: cosmosphere
    app.kubernetes.io/component: ingress
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`cosmosphere.harvestasya.org`)
    services:
    - name: cosmosphere-couchdb
      port: 5984
    middlewares:
    - name: cosmosphere-cors
    - name: security-headers
      namespace: traefik
  tls:
    secretName: harvestasya-wildcard-tls
