apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cosmosphere-couchdb-secret
  labels:
    app.kubernetes.io/name: cosmosphere
    app.kubernetes.io/component: couchdb
spec:
  # TODO: 1Passwordでアイテムを作成後、itemPathを更新してください
  # 必要なフィールド: username, password
  itemPath: "vaults/5mixaulvwor6zfvbfmtqlksdy4/items/cosmosphere-couchdb"
