apiVersion: v1
kind: Service
metadata:
  name: cosmosphere-couchdb
  labels:
    app.kubernetes.io/name: cosmosphere
    app.kubernetes.io/component: couchdb
spec:
  selector:
    app.kubernetes.io/name: cosmosphere
    app.kubernetes.io/component: couchdb
  ports:
  - port: 5984
    targetPort: 5984
    name: http
