apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: onepassword
resources:
- namespace.yaml
- networkpolicy.yaml

helmCharts:
# https://github.com/1Password/connect-helm-charts/tree/main/charts/connect
- name: connect
  releaseName: connect
  namespace: onepassword
  version: 2.3.0
  repo: https://1password.github.io/connect-helm-charts
  includeCRDs: true
  valuesInline:
    operator:
      # Operator disabled - using External Secrets Operator instead
      create: false
