apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: velaux
  namespace: vela-system
  annotations:
    # RBAC: /kubevela/admin (using claim/groups for OIDC)
    ingress.pomerium.io/policy: |
      - allow:
          or:
            - claim/groups: /kubevela/admin
    ingress.pomerium.io/pass_identity_headers: "true"
    ingress.pomerium.io/set_response_headers: |
      Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
      X-Frame-Options: SAMEORIGIN
      X-Content-Type-Options: nosniff
      X-XSS-Protection: 1; mode=block
      Referrer-Policy: same-origin
spec:
  ingressClassName: pomerium
  rules:
  - host: velaux.harvestasya.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: velaux-server
            port:
              number: 8000
