apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vela-system

resources:
- namespace.yaml
- traitdefinition-traefik-route.yaml
- componentdefinition-helm.yaml
- application-velaux.yaml
- ingress.yaml

helmCharts:
- name: vela-core
  releaseName: kubevela
  namespace: vela-system
  version: 1.10.6
  repo: https://kubevela.github.io/charts
  includeCRDs: true
  valuesFile: values.yaml
