apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-pomerium-route
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`traefik.harvestasya.org`)
    services:
    - name: pomerium-proxy
      namespace: pomerium
      port: 443
      scheme: https
      serversTransport: pomerium-transport
