apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secret-env
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: n8n-secret-env
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: n8n/n8n-secret-env
