apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: pomerium-transport
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-pomerium-route
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`reyvateils.harvestasya.org`)
    services:
    - name: pomerium-proxy
      namespace: pomerium
      port: 443
      scheme: https
      serversTransport: pomerium-transport
