apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n8n

resources:
- namespace.yaml
- cnpg-cluster.yaml
- pvc.yaml
- external-secret.yaml
- statefulset.yaml
- service.yaml
- ingress.yaml
- networkpolicy.yaml
