apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: argocd-notifications-secret
spec:
  # Same 1Password item as argocd-custom-secret
  itemPath: "vaults/5mixaulvwor6zfvbfmtqlksdy4/items/grepju7dv3cpwbzbpbof4she2m"
