apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: argocd-secret
spec:
  # Same 1Password item as argocd-custom-secret, but creates argocd-secret for webhook
  itemPath: "vaults/5mixaulvwor6zfvbfmtqlksdy4/items/grepju7dv3cpwbzbpbof4she2m"
