apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: couchdb

spec:
  routes:
  - kind: Rule
    match: Host(`livesync.harvestasya.org`)
    services:
    - name: couchdb
      port: 5984
