apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: obsidian-livesync

resources:
- namespace.yaml
- external-secret.yaml
- pvc.yaml
- configmap.yaml
- statefulset.yaml
- service.yaml
- ingressroute.yaml
- networkpolicy.yaml
