apiVersion: v1
kind: Service
metadata:
  name: couchdb
  labels:
    app.kubernetes.io/name: couchdb
spec:
  type: ClusterIP
  ports:
  - port: 5984
    targetPort: http
    protocol: TCP
    name: http
  - port: 9984
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: couchdb
