apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: voidauth

spec:
  routes:
  - kind: Rule
    match: Host(`qualia.harvestasya.org`)
    services:
    - name: voidauth
      port: 3000
