apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: voidauth
resources:
- cnpg-cluster.yaml
- deployment.yaml
- ingressroute.yaml
- namespace.yaml
- pvc.yaml
- secret-voidauth.yaml
- service.yaml

