apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: voidauth-config
  namespace: voidauth
  labels:
    app.kubernetes.io/name: voidauth
spec:
  itemPath: "vaults/5mixaulvwor6zfvbfmtqlksdy4/items/55g2ms4rbyopbs2xxosw654nyi"
